require("core.plugin-config.catppuccin")
require("core.plugin-config.barbecue")
require("core.plugin-config.dashboard-nvim")
require("core.plugin-config.lualine")
require("core.plugin-config.nvim-tree")
require("core.plugin-config.treesitter")
require("core.plugin-config.telescope")
